# Generated by Django 5.0 on 2024-01-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fac_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=18, null=True)),
                ('image', models.ImageField(upload_to='profile_pic/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('number', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='signup_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25, null=True)),
                ('l_name', models.CharField(max_length=15, null=True)),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('department', models.CharField(max_length=18, null=True)),
                ('image', models.ImageField(upload_to='profile_pic/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=12, null=True)),
                ('dob', models.DateField(null=True)),
                ('father', models.CharField(max_length=30, null=True)),
                ('mother', models.CharField(max_length=30, null=True)),
                ('number', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=8, null=True)),
                ('age', models.IntegerField(null=True)),
                ('income', models.IntegerField(null=True)),
                ('religion', models.CharField(max_length=16, null=True)),
                ('caste', models.CharField(max_length=14, null=True)),
                ('bloodgroup', models.CharField(max_length=8, null=True)),
                ('address', models.TextField(null=True)),
                ('district', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=25, null=True)),
                ('lang', models.TextField(null=True)),
                ('nation', models.CharField(max_length=30, null=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('userr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userr', 'date')},
            },
        ),
    ]
