# Generated by Django 5.0 on 2024-01-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_sign',
            name='image',
            field=models.ImageField(upload_to='teacher_pic/'),
        ),
    ]
