# Generated by Django 5.0 on 2024-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelink', '0002_alter_fac_sign_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('eligibility_criteria', models.TextField(null=True)),
                ('yearly_income', models.IntegerField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('S_caste', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
